
# config.py

region_mapping = {
    'Anglosphere': ['United States', 'Canada', 'United Kingdom', 'Ireland', 'New Zealand', 'Australia'],
    'Latin America': ['Argentina', 'Chile', 'Colombia', 'Ecuador', 'Guatemala', 'Mexico', 'Peru', 'Puerto Rico', 'Venezuela', 'Brazil', 'Bolivia', 'Paraguay', 'Uruguay'],
    'Middle East': ['Iraq', 'Saudi Arabia', 'United Arab Emirates', 'Yemen', 'Iran', 'Israel', 'Jordan', 'Kuwait', 'Lebanon', 'Oman', 'Qatar', 'Syria', 'Bahrain'],
    'French & Spanish Speaking Mainland Europe': ['Spain', 'France', 'Belgium', 'Switzerland', 'Portugal', 'Italy', 'Greece', 'Germany', 'Austria', 'Netherlands'],
    'West Africa': ['Cameroon', 'Cote d’Ivoire', 'Democratic Republic of the Congo', 'Nigeria', 'Ghana', 'Senegal', 'Mali', 'Niger', 'Guinea'],
    'North Africa': ['Algeria', 'Egypt', 'Morocco', 'Tunisia', 'Libya', 'Sudan'],
    'East & Southeast Asia': ['China', 'Japan', 'South Korea', 'North Korea', 'Vietnam', 'Thailand', 'Malaysia', 'Indonesia', 'Philippines', 'Singapore'],
    'South Asia': ['India', 'Pakistan', 'Bangladesh', 'Sri Lanka', 'Nepal', 'Bhutan'],
    'Eastern Europe & Central Asia': ['Russia', 'Ukraine', 'Belarus', 'Moldova', 'Armenia', 'Azerbaijan', 'Georgia', 'Kazakhstan', 'Uzbekistan', 'Turkmenistan', 'Kyrgyzstan', 'Tajikistan'],
    'Scandinavia & Baltic': ['Sweden', 'Norway', 'Finland', 'Denmark', 'Iceland', 'Estonia', 'Latvia', 'Lithuania'],
    'Oceania & Pacific Islands': ['Fiji', 'Papua New Guinea', 'Samoa', 'Solomon Islands', 'Tonga'],
    'Sub-Saharan Africa': ['Kenya', 'Uganda', 'Tanzania', 'Rwanda', 'Burundi', 'South Africa', 'Zimbabwe', 'Zambia', 'Botswana', 'Namibia', 'Mozambique', 'Madagascar'],
    'Central America & Caribbean': ['Cuba', 'Dominican Republic', 'Haiti', 'Jamaica', 'Trinidad and Tobago', 'Barbados', 'Saint Lucia', 'Grenada', 'Belize', 'Costa Rica', 'El Salvador', 'Honduras', 'Nicaragua', 'Panama']
    # ... You can continue to add more regions and countries as needed.
}


# Data schema selected with Tara

set1 = [
 'Overall MHQ',
 'MHQ_Sign',
 
 'Age',
 'Biological Sex',
#  'Different gender from biological sex',
#  'Gender Identity',
#  'Ethnicity',
 'Country',
#  'State',
#  'Place of living',
#  'City',
 'Education',
 'Employment',#  Yes
 'Region',
#  'Profession/Employment Sector',
 
 'Frequency of getting a good nights sleep',
 'Frequency of doing exercise',
 'Processed food in diet',
 'Frequency of Socializing',
 
#  'Number of Children',
#  'Household Size',
#  'Number of Siblings when growing up',
#  'Number of Close Friends',
 
#  'Description of Household Growing up',
#  'Relationship with Adult Family',
#  'Spirituality connection',
#  'Feelings of love towards others',
#  'Particular religion identity',
#  'Religion practice',

# smartphone with age<24
 
#  'Smartphone allowed in school',
#  'Smartphone use in lessons',
#  'Age of first social media account',
#  'Frequency of social media posting',
#  'Tablet ownership',
#  'Smartphone ownership',
#  'Friends/classmates smarphone ownership',
#  'Age of smartphone usage during school hours',
#  'Smartphone usage during class hours',
#  'Smartphone usage during break',
#  'Age of laptop usage required by school',
#  'Laptop usage for non-learning activities',

 'Sudden or premature death of a loved one',
 'Divorce/separation  or family breakup',
 'Extreme poverty leading to homelessness and/or hunger.',
 'Forced family control over major life decisions (e.g. marriage)',
 'Prolonged sexual abuse| or severe sexual assault.',
 'Displacement from your home due to political| environmental or economic reasons',
 'Loss of your job or livelihood leading to an inability to make ends meet.',
 'Cyberbullying or online abuse',
 'Threatening| coercive or controlling behavior by another person',
 'Caring for a child or partner with a major chronic disability or illness',
 'I did not experience any of the above',
 'Involvement or close witness to a war',
 'Life threatening or debilitating injury or illness.',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster',
 'None of the above AT',

#  'Type II Diabetes',
#  'Fibromyalgia',
#  'Liver disease/Cirrhosis',
#  'Hypertension',
#  'Irritable Bowel Syndrome',
#  'Heart disease',
#  "Inflammatory Bowel Disease / Crohn's disease",
#  'Arthritis',
#  'Psoriasis',
#  'Asthma',
#  'Migraines',
#  'Traumatic Brain Injury',
#  'Osteoporosis',
#  'Sleep apnea',
#  'Hipotiroidismo',
#  'Neuropathy',
#  'Cancer',
#  'Chronic Obstructive Pulmonary Disease (COPD)',
#  'HIV /AIDS',
#  'Kidney Disease',
#  'Rheumatoid',
#  'Polycystic ovaries',
#  'Prefer not to say',
#  'Narcolepsy',
#  'Chronic fatigue syndrome',
#  'Back problem',
#  'Epilepsy',
#  'Multiple sclerosis',
#  'Escoliosis',
#  'Stroke',
#  'Herpes',
#  'Type 1 Diabetes',

 'Sudden or premature death of a parent or sibling',
 'Prolonged emotional or psychological abuse or neglect from parent/caregiver',
 'Prolonged physical abuse| or severe physical assault CT',
 'Physical violence in the home between family members',
 'Prolonged or sustained bullying in person from peers',
 'Parental Divorce or family breakup',
 'Lived with a parent/caregiver who was an alcoholic or who regularly used street drugs',
 'Threatening| coercive or controlling behavior by another person CT',
 'I did not experience any of the above during my childhood',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster CT',
 'Displacement from your home due to political| environmental or economic reasons CT',
 'Life threatening or debilitating injury or illness CT',
 'Forced family control over major life decisions CT',
 'None of the above CT',

 'Tobacco products',
 'Alcoholic beverages',
 'Cannabis',
 'Vaping products',
 'Sedatives or Sleeping Pills',
 'Amphetamine type stimulants (e.g. speed| diet pills| ecstasy| etc.)',
 'Opioids',
 'Melatonina',
 'Cigarrillo',
 'None of the above']





to_model_a = ['Overall MHQ',
 'MHQ_Sign',
 'Sudden or premature death of a loved one',
 'Divorce/separation  or family breakup',
 'Extreme poverty leading to homelessness and/or hunger.',
 'Forced family control over major life decisions (e.g. marriage)',
 'Prolonged sexual abuse| or severe sexual assault.',
 'Displacement from your home due to political| environmental or economic reasons',
 'Loss of your job or livelihood leading to an inability to make ends meet.',
 'Cyberbullying or online abuse',
 'Threatening| coercive or controlling behavior by another person',
 'Caring for a child or partner with a major chronic disability or illness',
 'I did not experience any of the above',
 'Involvement or close witness to a war',
 'Life threatening or debilitating injury or illness.',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster',
 'None of the above AT',
 'Sudden or premature death of a parent or sibling',
 'Prolonged emotional or psychological abuse or neglect from parent/caregiver',
 'Prolonged physical abuse| or severe physical assault CT',
 'Physical violence in the home between family members',
 'Prolonged or sustained bullying in person from peers',
 'Parental Divorce or family breakup',
 'Lived with a parent/caregiver who was an alcoholic or who regularly used street drugs',
 'Threatening| coercive or controlling behavior by another person CT',
 'I did not experience any of the above during my childhood',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster CT',
 'Displacement from your home due to political| environmental or economic reasons CT',
 'Life threatening or debilitating injury or illness CT',
 'Forced family control over major life decisions CT',
 'None of the above CT',
 'Tobacco products',
 'Alcoholic beverages',
 'Cannabis',
 'Vaping products',
 'Sedatives or Sleeping Pills',
 'Amphetamine type stimulants (e.g. speed| diet pills| ecstasy| etc.)',
 'Opioids',
 'Melatonina',
 'Cigarrillo',
 
 'Biological Sex_Female',
 'Biological Sex_Male',
 'Biological Sex_Other/Intersex',
 'Biological Sex_Prefer not to say',
 
 'Frequency of getting a good nights sleep_All of the time',
 'Frequency of getting a good nights sleep_Hardly ever',
 'Frequency of getting a good nights sleep_Most days',
 'Frequency of getting a good nights sleep_Most of the time',
 'Frequency of getting a good nights sleep_Some of the time',
 
 'Frequency of doing exercise_Every day',
 'Frequency of doing exercise_Few days a week',
 'Frequency of doing exercise_Less than once a week',
 'Frequency of doing exercise_Once a week',
 'Frequency of doing exercise_Rarely/Never',
 'Frequency of doing exercise_Several days a week',
 #'Frequency of doing exercise_Some days of the week',
 'Processed food in diet_A few times a month',
 'Processed food in diet_A few times a week',
 'Processed food in diet_Once a day',
 'Processed food in diet_Rarely/Never',
 'Processed food in diet_Several times a day',
 'Frequency of Socializing_1-3 times a month',
 'Frequency of Socializing_Once a week',
 'Frequency of Socializing_Rarely/Never',
 'Frequency of Socializing_Several days a week']


to_model_c = [
    
 'Overall MHQ',
 'MHQ_Sign',
 'Sudden or premature death of a loved one',
 'Divorce/separation  or family breakup',
 'Extreme poverty leading to homelessness and/or hunger.',
 'Forced family control over major life decisions (e.g. marriage)',
 'Prolonged sexual abuse| or severe sexual assault.',
 'Displacement from your home due to political| environmental or economic reasons',
 'Loss of your job or livelihood leading to an inability to make ends meet.',
 'Cyberbullying or online abuse',
 'Threatening| coercive or controlling behavior by another person',
 'Caring for a child or partner with a major chronic disability or illness',
 'I did not experience any of the above',
 'Involvement or close witness to a war',
 'Life threatening or debilitating injury or illness.',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster',
 'None of the above AT',
 'Sudden or premature death of a parent or sibling',
 'Prolonged emotional or psychological abuse or neglect from parent/caregiver',
 'Prolonged physical abuse| or severe physical assault CT',
 'Physical violence in the home between family members',
 'Prolonged or sustained bullying in person from peers',
 'Parental Divorce or family breakup',
 'Lived with a parent/caregiver who was an alcoholic or who regularly used street drugs',
 'Threatening| coercive or controlling behavior by another person CT',
 'I did not experience any of the above during my childhood',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster CT',
 'Displacement from your home due to political| environmental or economic reasons CT',
 'Life threatening or debilitating injury or illness CT',
 'Forced family control over major life decisions CT',
 'None of the above CT',
 'Tobacco products',
 'Alcoholic beverages',
 'Cannabis',
 'Vaping products',
 'Sedatives or Sleeping Pills',
 'Amphetamine type stimulants (e.g. speed| diet pills| ecstasy| etc.)',
 'Opioids',
 'Melatonina',
 'Cigarrillo',
 
 'Age_18',
 'Age_18-24',
 'Age_19',
 'Age_20',
 'Age_21-24',
 'Age_25-34',
 'Age_35-44',
 'Age_45-54',
 'Age_55-64',
 'Age_65-74',
 'Age_75-84',
 'Age_85+',
 'Biological Sex_Female',
 'Biological Sex_Male',
 'Biological Sex_Other/Intersex',
 'Biological Sex_Prefer not to say',

#  'Country_Australia',
#  'Country_United Kingdom',
#  'Country_United States',
 
 
 'Frequency of getting a good nights sleep_All of the time',
 'Frequency of getting a good nights sleep_Hardly ever',
 'Frequency of getting a good nights sleep_Most days',
 'Frequency of getting a good nights sleep_Most of the time',
 'Frequency of getting a good nights sleep_Some of the time',
 'Frequency of doing exercise_Every day',
 'Frequency of doing exercise_Few days a week',
 'Frequency of doing exercise_Less than once a week',
 'Frequency of doing exercise_Once a week',
 'Frequency of doing exercise_Rarely/Never',
 #'Frequency of doing exercise_Several days a week',
 #'Frequency of doing exercise_Some days of the week',
 'Processed food in diet_A few times a month',
 'Processed food in diet_A few times a week',
 'Processed food in diet_Once a day',
 'Processed food in diet_Rarely/Never',
 'Processed food in diet_Several times a day',
 'Frequency of Socializing_1-3 times a month',
 'Frequency of Socializing_Once a week',
 'Frequency of Socializing_Rarely/Never',
 'Frequency of Socializing_Several days a week']




to_model_ac = [

 'Overall MHQ',
 'MHQ_Sign',
 'Sudden or premature death of a loved one',
 'Divorce/separation  or family breakup',
 'Extreme poverty leading to homelessness and/or hunger.',
 'Forced family control over major life decisions (e.g. marriage)',
 'Prolonged sexual abuse| or severe sexual assault.',
 'Displacement from your home due to political| environmental or economic reasons',
 'Loss of your job or livelihood leading to an inability to make ends meet.',
 'Cyberbullying or online abuse',
 'Threatening| coercive or controlling behavior by another person',
 'Caring for a child or partner with a major chronic disability or illness',
 'I did not experience any of the above',
 'Involvement or close witness to a war',
 'Life threatening or debilitating injury or illness.',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster',
 'None of the above AT',
 'Sudden or premature death of a parent or sibling',
 'Prolonged emotional or psychological abuse or neglect from parent/caregiver',
 'Prolonged physical abuse| or severe physical assault CT',
 'Physical violence in the home between family members',
 'Prolonged or sustained bullying in person from peers',
 'Parental Divorce or family breakup',
 'Lived with a parent/caregiver who was an alcoholic or who regularly used street drugs',
 'Threatening| coercive or controlling behavior by another person CT',
 'I did not experience any of the above during my childhood',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster CT',
 'Displacement from your home due to political| environmental or economic reasons CT',
 'Life threatening or debilitating injury or illness CT',
 'Forced family control over major life decisions CT',
 'None of the above CT',
 'Tobacco products',
 'Alcoholic beverages',
 'Cannabis',
 'Vaping products',
 'Sedatives or Sleeping Pills',
 'Amphetamine type stimulants (e.g. speed| diet pills| ecstasy| etc.)',
 'Opioids',
 'Melatonina',
 'Cigarrillo',
 
 
 
 'Biological Sex_Female',
 'Biological Sex_Male',
 'Biological Sex_Other/Intersex',
 'Biological Sex_Prefer not to say',
 
 
 
 'Frequency of getting a good nights sleep_All of the time',
 'Frequency of getting a good nights sleep_Hardly ever',
 'Frequency of getting a good nights sleep_Most days',
 'Frequency of getting a good nights sleep_Most of the time',
 'Frequency of getting a good nights sleep_Some of the time',
 'Frequency of doing exercise_Every day',
 'Frequency of doing exercise_Few days a week',
 'Frequency of doing exercise_Less than once a week',
 'Frequency of doing exercise_Once a week',
 'Frequency of doing exercise_Rarely/Never',
 'Processed food in diet_A few times a month',
 'Processed food in diet_A few times a week',
 'Processed food in diet_Once a day',
 'Processed food in diet_Rarely/Never',
 'Processed food in diet_Several times a day',
 'Frequency of Socializing_1-3 times a month',
 'Frequency of Socializing_Once a week',
 'Frequency of Socializing_Rarely/Never',
 'Frequency of Socializing_Several days a week']








to_model = [
 'Overall MHQ',
 'MHQ_Sign',
 'Sudden or premature death of a loved one',
 'Divorce/separation  or family breakup',
 'Extreme poverty leading to homelessness and/or hunger.',
 'Forced family control over major life decisions (e.g. marriage)',
 'Prolonged sexual abuse| or severe sexual assault.',
 'Displacement from your home due to political| environmental or economic reasons',
 'Loss of your job or livelihood leading to an inability to make ends meet.',
 'Cyberbullying or online abuse',
 'Threatening| coercive or controlling behavior by another person',
 'Caring for a child or partner with a major chronic disability or illness',
 'I did not experience any of the above',
 'Involvement or close witness to a war',
 'Life threatening or debilitating injury or illness.',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster',
 'None of the above AT',
 'Sudden or premature death of a parent or sibling',
 'Prolonged emotional or psychological abuse or neglect from parent/caregiver',
 'Prolonged physical abuse| or severe physical assault CT',
 'Physical violence in the home between family members',
 'Prolonged or sustained bullying in person from peers',
 'Parental Divorce or family breakup',
 'Lived with a parent/caregiver who was an alcoholic or who regularly used street drugs',
 'Threatening| coercive or controlling behavior by another person CT',
 'I did not experience any of the above during my childhood',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster CT',
 'Displacement from your home due to political| environmental or economic reasons CT',
 'Life threatening or debilitating injury or illness CT',
 'Forced family control over major life decisions CT',
 'None of the above CT',
 'Tobacco products',
 'Alcoholic beverages',
 'Cannabis',
 'Vaping products',
 'Sedatives or Sleeping Pills',
 'Amphetamine type stimulants (e.g. speed| diet pills| ecstasy| etc.)',
 'Opioids',
 'Melatonina',
 'Cigarrillo',
 

 'Age_18',
 'Age_18-24',
 'Age_19',
 'Age_20',
 'Age_21-24',
 'Age_25-34',
 'Age_35-44',
 'Age_45-54',
 'Age_55-64',
 'Age_65-74',
 'Age_75-84',
 'Age_85+',

 'Biological Sex_Female',
 'Biological Sex_Male',
 'Biological Sex_Other/Intersex',
 'Biological Sex_Prefer not to say',
 
 'Frequency of getting a good nights sleep_All of the time',
 'Frequency of getting a good nights sleep_Hardly ever',
 'Frequency of getting a good nights sleep_Most days',
 'Frequency of getting a good nights sleep_Most of the time',
 'Frequency of getting a good nights sleep_Some of the time',
 
 
 'Frequency of doing exercise_Every day',
 'Frequency of doing exercise_Few days a week',
 'Frequency of doing exercise_Less than once a week',
 'Frequency of doing exercise_Once a week',
 'Frequency of doing exercise_Rarely/Never',
 #'Frequency of doing exercise_Several days a week',
 #'Frequency of doing exercise_Some days of the week',
 
 
 
 'Frequency of doing exercise_Every day',
 'Frequency of doing exercise_Few days a week',
 'Frequency of doing exercise_Less than once a week',
 'Frequency of doing exercise_Once a week',
 'Frequency of doing exercise_Rarely/Never',
 'Frequency of doing exercise_Several days a week',
 'Frequency of doing exercise_Some days of the week',
 
 'Processed food in diet_A few times a month',
 'Processed food in diet_A few times a week',
 'Processed food in diet_Once a day',
 'Processed food in diet_Rarely/Never',
 'Processed food in diet_Several times a day',

 'Frequency of Socializing_1-3 times a month',
 'Frequency of Socializing_Once a week',
 'Frequency of Socializing_Rarely/Never',
 'Frequency of Socializing_Several days a week']



set10 = [
    
#  'Time to completion',
 'Overall MHQ',

#  'Cognition Dimension',
#  'Adaptability & Resilence Dimension',
#  'Drive & Motivation Dimension',
#  'Mood & Outlook Dimension',
#  'Social & Self Dimension',
#  'Mind Body Connection Dimension',
#  'Understanding of Assessment',
#  'Adaptability to Change',
#  'Self Worth & Confidence',
#  'Creativity & Problem Solving',
#  'Drive & Motivation',
#  'Stability & Calmness',
#  'Sleep Quality',
#  'Self Control & Impulsivity',
#  'Ability to Learn',
#  'Coordination',
#  'Relationships with others',
#  'Emotional Resilience',
#  'Planning & Organisation',
#  'Physical Intimacy',
#  'Speech & Language',
#  'Memory',
#  'Social interactions & Cooperation',
#  'Decision-making & Risk-taking',
#  'Curiosity, Interest & Enthusiasm',
#  'Energy Level',
#  'Emotional Control',
#  'Focus & Concentration',
#  'Appetite Regulation',
#  'Empathy',
#  'Sensory Sensitivity',
#  'Self-Image',
#  'Outlook & Optimism',
#  'Selective Attention',
#  'Restlessness & Hyperactivity',
#  'Fear & Anxiety',
#  'Susceptibility to Infections',
#  'Aggression Towards Others',
#  'Avoidance & Withdrawal',
#  'Unwanted, Strange or Obsessive Thoughts',
#  'ARCHIVED: Primary nature of strange, unwanted or obsessive thoughts',
#  'Mood Swings',
#  'Sense of being detached from reality',
#  'Nightmares',
#  'Addictions',
#  'Anger & Irritability',
#  'Suicidal Thoughts or Intentions',
#  'Experience of Pain',
#  'Guilt & Blame',
#  'ARCHIVED: Options that best describe your feelings of Guilt and Blame',
#  'Hallucinations',
#  'Traumatic Flashbacks',
#  'Repetitive or Compulsive Actions',
#  'Feelings of Sadness, Distress or Hopelessness',
#  'Physical Health Issues',
#  'Confusion or Slowed Thinking',

 'Age',
 'Biological Sex',
 'Education',
 'Employment',



#  'Different gender from biological sex',
#  'Gender Identity',
#  'ARCHIVED: Gender',
#  'Ethnicity',

 'Country',

#  'State',
#  'Place of living',
#  'City',
 
#  'Profession/Employment Sector',
#  'ARCHIVED: Job Role',


 'Household Income',
 'Language',


#  'ARCHIVED: Productivity Benchmarking (unable to work)',
#  'ARCHIVED: Productivity Benchmarking (unproductive work)',



 'Frequency of getting a good nights sleep',
 'Frequency of doing exercise',
 'Processed food in diet',
 'Frequency of Socializing',




#  'Substance Use',
#  'Presence/Absence of Diagnosed Medical Disorder',
#  'Type of Medical Condition',
#  'Mental Health Treatment Status',
#  'Not seeking help reasons',
#  'Type of Treatment (revised 2023)',
#  'ARCHIVED: Type of Treatment',
#  'Effectiveness of therapy treatment',
#  'Effectiveness of medication treatment',
#  'Effectiveness of brain stimulation treatment',
#  'Effectiveness of neurofeedback treatment',
#  'Diagnosed mental health disorders',
#  'Childhood traumas',
#  'Adult traumas',
#  'ARCHIVED: Life Trauma (pre-2022)',
#  'Current Family Situation',
#  'Number of Children',
#  'Household Size',
#  'Number of Siblings when growing up',
#  'Number of Close Friends',
#  'ARCHIVED: Childhood Friends',
#  'ARCHIVED: Proximity of Close Friends',
#  'ARCHIVED: Friendship (type of interaction)',
#  'Friendship (help you out)',
#  'ARCHIVED:riendship (confide in)',
#  'ARCHIVED: Nature of Household Growing up',
#  'Description of Household Growing up',
#  'ARCHIVED: Parental/caregiver support',
#  'ARCHIVED: Proximity of Adult Family',
#  'Relationship with Adult Family',
#  'Spirituality connection',
#  'Feelings of love towards others',
#  'Particular religion identity',
#  'Religion practice',
#  'ARCHIVED: Individualism vs collectivism',


 'ARCHIVED: Smartphone ownership',
 'ARCHIVED: Age of smartphone access',
 'Smartphone allowed in school',
 'Smartphone use in lessons',

 'Smartphone ownership',
 'Friends/classmates smarphone ownership',
 'Age of smartphone usage during school hours',
 'Smartphone usage during class hours',
 'Smartphone usage during break',


#  'ARCHIVED: Internet restriction as a teenager',
#  'Age of first social media account',
#  'Frequency of social media posting',
#  'Tablet ownership',




#  'Age of laptop usage required by school',
#  'Laptop usage for non-learning activities',
#  'ARCHIVED: PHQ-9 - Interest',
#  'ARCHIVED: PHQ-9 - Depressed',
#  'ARCHIVED: PHQ-9 - Sleep',
#  'ARCHIVED: PHQ-9 - Energy',
#  'ARCHIVED: PHQ-9 - Failure',
#  'ARCHIVED: PHQ-9 - Appetite',
#  'ARCHIVED: PHQ-9 - Concentration',
#  'ARCHIVED: PHQ-9 - Slow movements',
#  'ARCHIVED: PHQ-9 - Self harm',
#  'ARCHIVED: GAD-7 - Feeling nervous',
#  'ARCHIVED: GAD-7 - Worrying',
#  'ARCHIVED: GAD-7 - Self-control',
#  'ARCHIVED: GAD-7 - Trouble relaxing',
#  'ARCHIVED: GAD-7 - Restless',
#  'ARCHIVED: GAD-7 - Annoyed or irritable',
#  'ARCHIVED: GAD-7 - Feeling afraid',
#  'ARCHIVED: GAD-7 - Impact of the problems',
#  'ARCHIVED: Life Satisfaction',
#  'ARCHIVED: Time of day',
#  'ARCHIVED: Mood',
#  'ARCHIVED: Alertness',
#  'ARCHIVED: Hours Sleep Previous Night',
#  'ARCHIVED: Time Since Last Meal',
#  'ARCHIVED: Physical complaints',
#  'ARCHIVED: Pregnant',
#  'ARCHIVED: Covid: health & social adversities',
#  'ARCHIVED: Covid: financial adversities',
#  'ARCHIVED: Depression Benchmarking (frequency)',
#  'ARCHIVED: Depression Benchmarking (severity)',
#  'Admin Use 1',
#  'Admin Use 2',
#  'Admin Use 3',
#  'Repeat identifier',



 'MHQ_Sign',
 'Sudden or premature death of a loved one',
 'Divorce/separation  or family breakup',
 'Extreme poverty leading to homelessness and/or hunger.',
 'Forced family control over major life decisions (e.g. marriage)',
 'Prolonged sexual abuse| or severe sexual assault.',
 'Displacement from your home due to political| environmental or economic reasons',
 'Loss of your job or livelihood leading to an inability to make ends meet.',
 'Cyberbullying or online abuse',
 'Threatening| coercive or controlling behavior by another person',
 'Caring for a child or partner with a major chronic disability or illness',
 'I did not experience any of the above',
 'Involvement or close witness to a war',
 'Life threatening or debilitating injury or illness.',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster',
 'None of the above AT',



#  'Type II Diabetes',
#  'Fibromyalgia',
#  'Liver disease/Cirrhosis',
#  'Hypertension',
#  'Irritable Bowel Syndrome',
#  'Heart disease',
#  "Inflammatory Bowel Disease / Crohn's disease",
#  'Arthritis',
#  'Psoriasis',
#  'Asthma',
#  'Migraines',
#  'Traumatic Brain Injury',
#  'Osteoporosis',
#  'Sleep apnea',
#  'Hipotiroidismo',
#  'Neuropathy',
#  'Cancer',
#  'Chronic Obstructive Pulmonary Disease (COPD)',
#  'HIV /AIDS',
#  'Kidney Disease',
#  'Rheumatoid',
#  'Polycystic ovaries',
#  'Prefer not to say',
#  'Narcolepsy',
#  'Chronic fatigue syndrome',
#  'Back problem',
#  'Epilepsy',
#  'Multiple sclerosis',
#  'Escoliosis',
#  'Stroke',
#  'Herpes',
#  'Type 1 Diabetes',


 'Sudden or premature death of a parent or sibling',
 'Prolonged emotional or psychological abuse or neglect from parent/caregiver',
 'Prolonged physical abuse| or severe physical assault CT',
 'Physical violence in the home between family members',
 'Prolonged or sustained bullying in person from peers',
 'Parental Divorce or family breakup',
 'Lived with a parent/caregiver who was an alcoholic or who regularly used street drugs',
 'Threatening| coercive or controlling behavior by another person CT',
 'I did not experience any of the above during my childhood',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster CT',
 'Displacement from your home due to political| environmental or economic reasons CT',
 'Life threatening or debilitating injury or illness CT',
 'Forced family control over major life decisions CT',
 'None of the above CT',

 'Tobacco products',
 'Alcoholic beverages',
 'Cannabis',
 'Vaping products',
 'Sedatives or Sleeping Pills',
 'Amphetamine type stimulants (e.g. speed| diet pills| ecstasy| etc.)',
 'Opioids',
 'Melatonina',
 'Cigarrillo']




# New set of features


Legal_Substance_Use = [
    'Tobacco products',
    'Alcoholic beverages',
    'Cannabis',
    'Vaping products',
    'Sedatives or Sleeping Pills',
    'Amphetamine type stimulants (e.g. speed| diet pills| ecstasy| etc.)',
    'Opioids',
    'Melatonina',
    'Cigarrillo'
]

Interpersonal_Trauma = [
    'Prolonged emotional or psychological abuse or neglect from parent/caregiver',
    'Physical violence in the home between family members',
    'Prolonged or sustained bullying in person from peers',
    'Prolonged physical abuse| or severe physical assault CT',
    'Threatening| coercive or controlling behavior by another person CT',
    'Threatening| coercive or controlling behavior by another person',
    'Prolonged sexual abuse| or severe sexual assault.',
    'Cyberbullying or online abuse',
    'Forced family control over major life decisions (e.g. marriage)',
    'Forced family control over major life decisions CT'
]

Life_Adversities = [
    'Sudden or premature death of a loved one',
    'Parental Divorce or family breakup',
    'Divorce/separation  or family breakup',
    'Extreme poverty leading to homelessness and/or hunger.',
    'Sudden or premature death of a parent or sibling',
    'Loss of your job or livelihood leading to an inability to make ends meet.',
    'Lived with a parent/caregiver who was an alcoholic or who regularly used street drugs',
    'Life threatening or debilitating injury or illness.',
    'Suffered a loss in a major fire| flood| earthquake| or natural disaster',
    'Displacement from your home due to political| environmental or economic reasons CT',
    'Suffered a loss in a major fire| flood| earthquake| or natural disaster CT',
    'Life threatening or debilitating injury or illness CT',
    'Displacement from your home due to political| environmental or economic reasons',
    'Involvement or close witness to a war',
    'Caring for a child or partner with a major chronic disability or illness'
]




