



smartphone_set1 = [

#  'Unnamed: 0',

 'Language',
 'Start Date (UTC)',
 'Submit Date (UTC)',
 'Time to completion',
 
    

#  'Cognition Dimension',
#  'Adaptability & Resilence Dimension',
#  'Drive & Motivation Dimension',
#  'Mood & Outlook Dimension',
#  'Social & Self Dimension',
#  'Mind Body Connection Dimension',
#  'Understanding of Assessment',
#  'Adaptability to Change',
#  'Self Worth & Confidence',
#  'Creativity & Problem Solving',
#  'Drive & Motivation',
#  'Stability & Calmness',
#  'Sleep Quality',
#  'Self Control & Impulsivity',
#  'Ability to Learn',
#  'Coordination',
#  'Relationships with others',
#  'Emotional Resilience',
#  'Planning & Organisation',
#  'Physical Intimacy',
#  'Speech & Language',
#  'Memory',
#  'Social interactions & Cooperation',
#  'Decision-making & Risk-taking',
#  'Curiosity, Interest & Enthusiasm',
#  'Energy Level',
#  'Emotional Control',
#  'Focus & Concentration',
#  'Appetite Regulation',
#  'Empathy',
#  'Sensory Sensitivity',
#  'Self-Image',
#  'Outlook & Optimism',
#  'Selective Attention',
#  'Restlessness & Hyperactivity',
#  'Fear & Anxiety',
#  'Susceptibility to Infections',
#  'Aggression Towards Others',
#  'Avoidance & Withdrawal',
#  'Unwanted, Strange or Obsessive Thoughts',
#  'ARCHIVED: Primary nature of strange, unwanted or obsessive thoughts',
#  'Mood Swings',
#  'Sense of being detached from reality',
#  'Nightmares',
#  'Addictions',
#  'Anger & Irritability',
#  'Suicidal Thoughts or Intentions',
#  'Experience of Pain',
#  'Guilt & Blame',
#  'ARCHIVED: Options that best describe your feelings of Guilt and Blame',
#  'Hallucinations',
#  'Traumatic Flashbacks',
#  'Repetitive or Compulsive Actions',
#  'Feelings of Sadness, Distress or Hopelessness',
#  'Physical Health Issues',
#  'Confusion or Slowed Thinking',


 'Age',
 'Biological Sex',


#  'ARCHIVED: Different gender from biological sex',
#  'Gender Identity',
#  'ARCHIVED: Gender',


 'Ethnicity',
 'Country',
 'State',
 'Place of living',
 'City',
 'Education',
 'Employment',



#  'Belong to veteran',
#  'ARCHIVED: Profession/Employment Sector',
#  'ARCHIVED: Job Role',


 'Household Income',
#  'ARCHIVED: Productivity Benchmarking (unable to work)',
#  'ARCHIVED: Productivity Benchmarking (unproductive work)',


 'Frequency of getting a good nights sleep',
 'Frequency of doing exercise',
 'Processed food in diet',
 'Fresh fruit/vegetable consumption',
 'Sweet/sugary food or desserts consumption',
 'Frequency of Socializing',


#  'Substance Use',
#  'Presence/Absence of Diagnosed Medical Disorder',
#  'Type of Medical Condition',
#  'ARCHIVED: Mental Health Treatment Status',
#  'ARCHIVED: Not seeking help reasons',
#  'ARCHIVED: Type of Treatment (revised 2023)',
#  'ARCHIVED: Type of Treatment',
#  'ARCHIVED: Effectiveness of therapy treatment',
#  'ARCHIVED: Effectiveness of medication treatment',
#  'ARCHIVED: Effectiveness of brain stimulation treatment',
#  'ARCHIVED: Effectiveness of neurofeedback treatment',
#  'ARCHIVED: Diagnosed mental health disorders',
#  'Childhood traumas',
#  'Adult traumas',
#  'ARCHIVED: Life Trauma (pre-2022)',


 'Current Family Situation',
 'Number of Children',
 'Household Size',
 'Number of Siblings when growing up',
 'Number of Close Friends',



#  'ARCHIVED: Childhood Friends',
#  'ARCHIVED: Proximity of Close Friends',
#  'ARCHIVED: Friendship (type of interaction)',
#  'Friendship (help you out)',
#  'ARCHIVED: Friendship (confide in)',
#  'ARCHIVED: Nature of Household Growing up',
#  'Description of Household Growing up',
#  'ARCHIVED: Parental/caregiver support',
#  'ARCHIVED: Proximity of Adult Family',
#  'Relationship with Adult Family',
#  'Spirituality connection',
#  'Feelings of love towards others',
#  'Religious identity',
#  'Religion practice',
#  'ARCHIVED: Individualism vs collectivism',
#  'Productive days last month',
#  'Unproductive days last month',
#  'ARCHIVED: Smartphone ownership',
#  'ARCHIVED: Age of smartphone access',
#  'ARCHIVED: Smartphone allowed in school',
#  'ARCHIVED: Smartphone use in lessons',
#  'ARCHIVED: Internet restriction as a teenager',



 'Age of first social media account',
 'Frequency of social media posting',
 'Tablet ownership',

#  'ARCHIVED: Age of smartphone/tablet ownership',

 'Smartphone ownership',
 'Friends/classmates smartphone ownership',
 'Age of smartphone usage during school hours',
 'Smartphone usage during class hours',
 'Smartphone usage during break',

 
 'Age of laptop usage required by school',
 'Laptop usage for non-learning activities',


#  'ARCHIVED: PHQ-9 - Interest',
#  'ARCHIVED: PHQ-9 - Depressed',
#  'ARCHIVED: PHQ-9 - Sleep',
#  'ARCHIVED: PHQ-9 - Energy',
#  'ARCHIVED: PHQ-9 - Failure',
#  'ARCHIVED: PHQ-9 - Appetite',
#  'ARCHIVED: PHQ-9 - Concentration',
#  'ARCHIVED: PHQ-9 - Slow movements',
#  'ARCHIVED: PHQ-9 - Self harm',
#  'ARCHIVED: GAD-7 - Feeling nervous',
#  'ARCHIVED: GAD-7 - Worrying',
#  'ARCHIVED: GAD-7 - Self-control',
#  'ARCHIVED: GAD-7 - Trouble relaxing',
#  'ARCHIVED: GAD-7 - Restless',
#  'ARCHIVED: GAD-7 - Annoyed or irritable',
#  'ARCHIVED: GAD-7 - Feeling afraid',
#  'ARCHIVED: GAD-7 - Impact of the problems',
#  'ARCHIVED: Life Satisfaction',
#  'ARCHIVED: Time of day',
#  'ARCHIVED: Mood',
#  'ARCHIVED: Alertness',
#  'ARCHIVED: Hours Sleep Previous Night',
#  'ARCHIVED: Time Since Last Meal',
#  'ARCHIVED: Physical complaints',
#  'ARCHIVED: Pregnant',
#  'ARCHIVED: Covid: health & social adversities',
#  'ARCHIVED: Covid: financial adversities',
#  'ARCHIVED: Depression Benchmarking (frequency)',
#  'ARCHIVED: Depression Benchmarking (severity)',
#  'Admin Use 1',
#  'Admin Use 2',
#  'Admin Use 3',
#  'Admin Use 4',
#  'Admin Use 5',
#  'Repeat identifier',


 'MHQ_Sign',


 'Sudden or premature death of a loved one',
 'Divorce/separation  or family breakup',
 'Extreme poverty leading to homelessness and/or hunger.',
 'Forced family control over major life decisions (e.g. marriage)',
 'Prolonged sexual abuse| or severe sexual assault.',
 'Displacement from your home due to political| environmental or economic reasons',
 'Loss of your job or livelihood leading to an inability to make ends meet.',
 'Cyberbullying or online abuse',
 'Threatening| coercive or controlling behavior by another person',
 'Caring for a child or partner with a major chronic disability or illness',
 'I did not experience any of the above',
 'Involvement or close witness to a war',
 'Life threatening or debilitating injury or illness.',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster',
 'None of the above AT',
 'Type II Diabetes',
 'Fibromyalgia',
 'Liver disease/Cirrhosis',
 'Hypertension',
 'Irritable Bowel Syndrome',
 'Heart disease',
 "Inflammatory Bowel Disease / Crohn's disease",
 'Arthritis',
 'Psoriasis',
 'Asthma',
 'Migraines',
 'Traumatic Brain Injury',
 'Osteoporosis',
 'Sleep apnea',
 'Hipotiroidismo',
 'Neuropathy',
 'Cancer',
 'Chronic Obstructive Pulmonary Disease (COPD)',
 'HIV /AIDS',
 'Kidney Disease',
 'Rheumatoid',
 'Polycystic ovaries',
 'Prefer not to say',
 'Narcolepsy',
 'Chronic fatigue syndrome',
 'Back problem',
 'Epilepsy',
 'Multiple sclerosis',
 'Escoliosis',
 'Stroke',
 'Herpes',
 'Type 1 Diabetes',
 'Sudden or premature death of a parent or sibling',
 'Prolonged emotional or psychological abuse or neglect from parent/caregiver',
 'Prolonged physical abuse| or severe physical assault CT',
 'Physical violence in the home between family members',
 'Prolonged or sustained bullying in person from peers',
 'Parental Divorce or family breakup',
 'Lived with a parent/caregiver who was an alcoholic or who regularly used street drugs',
 'Threatening| coercive or controlling behavior by another person CT',
 'I did not experience any of the above during my childhood',
 'Suffered a loss in a major fire| flood| earthquake| or natural disaster CT',
 'Displacement from your home due to political| environmental or economic reasons CT',
 'Life threatening or debilitating injury or illness CT',
 'Forced family control over major life decisions CT',
 'None of the above CT',
 'Tobacco products',
 'Alcoholic beverages',
 'Cannabis',
 'Vaping products',
 'Sedatives or Sleeping Pills',
 'Amphetamine type stimulants (e.g. speed| diet pills| ecstasy| etc.)',
 'Opioids',
 'Melatonina',
 'Cigarrillo',
 'None of the above',
 'Overall MHQ',
 'MHQ_Sign'
]















